#!/bin/bash

# Dependencies:
# ffmpeg
# i3lock-color-git

IMAGE=/tmp/i3lock.png
TEXT="locked"
SCRIPT=`realpath $0`
SCRIPTPATH=`dirname $SCRIPT`/../share/i3-blur
LOCK=$SCRIPTPATH/lock.png
RES=$(xrandr --current | grep '*' | uniq | awk '{print $1}')
#This is a bit cheaty
BOXSIZE=$(expr $(echo $RES | cut -d 'x' -f1) / 2)

if [[ $1 != "" ]]; then
    TEXT=$1
fi

/usr/bin/ffmpeg -f x11grab -video_size $RES -y -i $DISPLAY -i $LOCK -filter_complex "boxblur=5,overlay=(main_w-overlay_w)/2:(main_h-overlay_h)/2" -vframes 1 $IMAGE



i3lock -i $IMAGE -n

rm $IMAGE
